M48
; DRILL file {KiCad 9.0.2} date 2025-06-16T14:42:46-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-16T14:42:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X25.85Y80.43
X58.87Y28.36
X74.11Y79.16
T2
X8.94Y98.63
X9.0Y7.9
X91.44Y98.63
X91.5Y7.9
M30
