M48
; DRILL file {KiCad 9.0.3} date 2025-08-16T16:26:42-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-16T16:26:42-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X5.0Y95.0
X5.0Y5.0
X25.84Y63.42
X58.86Y11.35
X74.1Y62.15
X95.0Y95.0
X95.0Y5.0
M30
